package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// writeGoFile writes Go source code to a file, formatting it first.
// If formatting fails, writes the raw bytes with .raw suffix for debugging.
func writeGoFile(path string, code []byte) error {
	formatted, err := format.Source(code)
	if err != nil {
		if wErr := os.WriteFile(path+".raw", code, 0644); wErr != nil {
			fmt.Fprintf(os.Stderr, "failed to write raw file: %v\n", wErr)
		}
		return fmt.Errorf("gofmt %s: %w", filepath.Base(path), err)
	}
	return os.WriteFile(path, formatted, 0644)
}

// walkXMLFiles returns all *.xml files under dir (recursive).
func walkXMLFiles(dir string) ([]string, error) {
	var files []string
	if err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(strings.ToLower(path), ".xml") {
			files = append(files, path)
		}
		return nil
	}); err != nil {
		return nil, fmt.Errorf("walking %s: %w", dir, err)
	}
	sort.Strings(files)
	return files, nil
}

// globXMLFiles returns *.xml files in a single directory (non-recursive).
func globXMLFiles(dir string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.xml"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}
	sort.Strings(files)
	return files, nil
}

// escapeString escapes a string for use in Go string literals.
func escapeString(s string) string {
	return strings.ReplaceAll(
		strings.ReplaceAll(
			strings.ReplaceAll(s, `\`, `\\`),
			`"`, `\"`),
		"\n", `\n`)
}

// sortedKeys returns sorted keys from a map.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// writeHeader writes the standard generated file header.
func writeHeader(buf *bytes.Buffer, generator string) {
	fmt.Fprintf(buf, "// Code generated by cmd/gendata/%s; DO NOT EDIT.\n\npackage data\n\n", generator)
}
