// Code generated by cmd/gendata/playerconfig; DO NOT EDIT.

package data

var initialEquipDefs = []initialEquipDef{
	{classID: 0, items: []initialItemDef{{itemID: 2369, count: 1, equipped: true}, {itemID: 10, count: 1}, {itemID: 1146, count: 1, equipped: true}, {itemID: 1147, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 10, items: []initialItemDef{{itemID: 6, count: 1, equipped: true}, {itemID: 425, count: 1, equipped: true}, {itemID: 461, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 18, items: []initialItemDef{{itemID: 2369, count: 1, equipped: true}, {itemID: 10, count: 1}, {itemID: 1146, count: 1, equipped: true}, {itemID: 1147, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 25, items: []initialItemDef{{itemID: 6, count: 1, equipped: true}, {itemID: 425, count: 1, equipped: true}, {itemID: 461, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 31, items: []initialItemDef{{itemID: 2369, count: 1, equipped: true}, {itemID: 10, count: 1}, {itemID: 1146, count: 1, equipped: true}, {itemID: 1147, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 38, items: []initialItemDef{{itemID: 6, count: 1, equipped: true}, {itemID: 425, count: 1, equipped: true}, {itemID: 461, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 44, items: []initialItemDef{{itemID: 2369, count: 1}, {itemID: 2368, count: 1, equipped: true}, {itemID: 1146, count: 1, equipped: true}, {itemID: 1147, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 49, items: []initialItemDef{{itemID: 2368, count: 1, equipped: true}, {itemID: 425, count: 1, equipped: true}, {itemID: 461, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
	{classID: 53, items: []initialItemDef{{itemID: 2370, count: 1, equipped: true}, {itemID: 10, count: 1}, {itemID: 1146, count: 1, equipped: true}, {itemID: 1147, count: 1, equipped: true}, {itemID: 5588, count: 1}}},
}

var initialShortcutsDefs = []initialShortcutsDef{
	{classID: -1, shortcuts: []shortcutDef{
		{page: 0, slot: 0, shortcutType: "ACTION", shortcutID: 2},
		{page: 0, slot: 3, shortcutType: "ACTION", shortcutID: 5},
		{page: 0, slot: 10, shortcutType: "ACTION", shortcutID: 0},
		{page: 0, slot: 11, shortcutType: "ITEM", shortcutID: 5588},
		{page: 1, slot: 0, shortcutType: "MACRO", shortcutID: 10000},
	}},
	{classID: 10, shortcuts: []shortcutDef{
		{page: 0, slot: 1, shortcutType: "SKILL", shortcutID: 1177, shortcutLevel: 1},
		{page: 0, slot: 9, shortcutType: "SKILL", shortcutID: 1216, shortcutLevel: 1},
	}},
	{classID: 25, shortcuts: []shortcutDef{
		{page: 0, slot: 1, shortcutType: "SKILL", shortcutID: 1177, shortcutLevel: 1},
		{page: 0, slot: 9, shortcutType: "SKILL", shortcutID: 1216, shortcutLevel: 1},
	}},
	{classID: 38, shortcuts: []shortcutDef{
		{page: 0, slot: 1, shortcutType: "SKILL", shortcutID: 1177, shortcutLevel: 1},
		{page: 0, slot: 9, shortcutType: "SKILL", shortcutID: 1216, shortcutLevel: 1},
	}},
	{classID: 49, shortcuts: []shortcutDef{
		{page: 0, slot: 1, shortcutType: "SKILL", shortcutID: 1001, shortcutLevel: 1},
	}},
}
