package model

import (
	"sync"
	"sync/atomic"
)

// Npc represents a non-player character in the world
type Npc struct {
	*Character // embedding Character (which embeds WorldObject)

	templateID int32
	template   *NpcTemplate

	mu         sync.RWMutex
	spawn      *Spawn
	isDecayed  atomic.Bool
	intention  atomic.Int32 // Intention type
}

// NewNpc creates a new NPC instance
// objectID should be generated by World/SpawnManager
func NewNpc(objectID uint32, templateID int32, template *NpcTemplate) *Npc {
	if template == nil {
		panic("NewNpc: template cannot be nil")
	}

	// Create Character with stats from template
	// Location will be set by SpawnManager via SetLocation
	character := NewCharacter(
		objectID,
		template.Name(),
		Location{}, // zero location, will be set later
		template.Level(),
		template.MaxHP(),
		template.MaxMP(),
		0, // CP not used for NPCs
	)

	npc := &Npc{
		Character:  character,
		templateID: templateID,
		template:   template,
	}

	// Set initial intention to IDLE
	npc.intention.Store(int32(IntentionIdle))
	npc.isDecayed.Store(false)

	// Phase 5.6: Set WorldObject.Data reference for PvE combat
	npc.WorldObject.Data = npc

	return npc
}

// TemplateID returns NPC template ID
func (n *Npc) TemplateID() int32 {
	return n.templateID
}

// Template returns NPC template
func (n *Npc) Template() *NpcTemplate {
	return n.template
}

// SetSpawn sets spawn point for this NPC
func (n *Npc) SetSpawn(spawn *Spawn) {
	n.mu.Lock()
	defer n.mu.Unlock()
	n.spawn = spawn
}

// Spawn returns spawn point for this NPC
func (n *Npc) Spawn() *Spawn {
	n.mu.RLock()
	defer n.mu.RUnlock()
	return n.spawn
}

// IsDecayed returns whether NPC is decayed (corpse disappeared)
func (n *Npc) IsDecayed() bool {
	return n.isDecayed.Load()
}

// SetDecayed sets decayed state
func (n *Npc) SetDecayed(decayed bool) {
	n.isDecayed.Store(decayed)
}

// Intention returns current AI intention (atomic read)
func (n *Npc) Intention() Intention {
	return Intention(n.intention.Load())
}

// SetIntention sets AI intention (atomic write)
func (n *Npc) SetIntention(intention Intention) {
	n.intention.Store(int32(intention))
}

// PAtk returns physical attack from template
func (n *Npc) PAtk() int32 {
	return n.template.PAtk()
}

// PDef returns physical defense from template
func (n *Npc) PDef() int32 {
	return n.template.PDef()
}

// MAtk returns magical attack from template
func (n *Npc) MAtk() int32 {
	return n.template.MAtk()
}

// MDef returns magical defense from template
func (n *Npc) MDef() int32 {
	return n.template.MDef()
}

// MoveSpeed returns movement speed from template
func (n *Npc) MoveSpeed() int32 {
	return n.template.MoveSpeed()
}

// AtkSpeed returns attack speed from template
func (n *Npc) AtkSpeed() int32 {
	return n.template.AtkSpeed()
}

// Title returns NPC title from template
func (n *Npc) Title() string {
	return n.template.Title()
}
