-- +goose Up
-- Phase 8.1+: Add character appearance and clan fields.
-- These fields are needed for CharSelectionInfo, CharSelected, UserInfo packets.

ALTER TABLE characters ADD COLUMN IF NOT EXISTS sex SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS face SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS hair_style SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS hair_color SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS karma INTEGER NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS clan_id BIGINT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS delete_timer BIGINT NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS sp BIGINT NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE characters DROP COLUMN IF EXISTS sp;
ALTER TABLE characters DROP COLUMN IF EXISTS delete_timer;
ALTER TABLE characters DROP COLUMN IF EXISTS clan_id;
ALTER TABLE characters DROP COLUMN IF EXISTS karma;
ALTER TABLE characters DROP COLUMN IF EXISTS hair_color;
ALTER TABLE characters DROP COLUMN IF EXISTS hair_style;
ALTER TABLE characters DROP COLUMN IF EXISTS face;
ALTER TABLE characters DROP COLUMN IF EXISTS sex;
